# Generated by Django 4.2.5 on 2023-09-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='Company',
        ),
    ]
