# Generated by Django 4.2.5 on 2023-09-24 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalouge', '0003_alter_category_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
    ]
